### ISSUE TITLE
Conflict with Elementor Pro (2.9.1)

### ISSUE THREAD

**Issue by simplixi** [dbjpanda/actions-pack-issue-tracker#14]
Hello,
I have a conclict with Actions pack and last version of Elementor Pro > When Actions Pack is activate Elementor (2.9.1) doesn't load.
Any idea please to fix that?
Regards
Thx for your help

**Comment by dbjpanda** [comment]
Could you please paste the exact error message you are seeing?

**Comment by simplixi** [comment]
Hey, i don’t have any message but when i try to modify my template with elementor, the elementor widget panel not loading (continuously spinning), and when i desactivate your plugin that’s works.
Exemple that i got : https://docs.elementor.com/article/576-elementor-widget-panel-not-loading <https://docs.elementor.com/article/576-elementor-widget-panel-not-loading>
Thx for your help (i really like ur plugin :-)
Stéphane




Stéphane Béguin [Simplixi]
Facilitation graphique et video scribing
stbeguin@simplixi.fr
+33 (0)7 49 11 18 51
–––––––––––––––––––––––––––––––
www.simplixi.fr <http://www.simplixi.fr/>
www.video-scribing.fr <http://www.video-scribing.fr/>
www.scribers.fr <http://www.scribers.fr/>

**Comment by dbjpanda** [comment]
Fixed in Actions Pack 1.3.0

**Comment by simplixi** [comment]
Hey, thx!!!! great support, that works perfectly!
Regards
Stéphane
