### ISSUE TITLE
How to create a reset password form.

### ISSUE THREAD

**Issue by dbjpanda** [dbjpanda/actions-pack-issue-tracker#23]
Currently we don't have a tutorial on it. But configuration is same as Registration.

1. Create a new password page. Note it's a page. Drag and drop the Elementor form. Create two fields 'password' and 'confirm password'. Set the action to "new password". Remeber the page's permalink.

2. Create a form of having one field 'username or email' .
Set the Action to 'reset pass'. And in configuration, map the field id as you do in Registration Action. Paste the permalink that you copied from above. 

Done

**Comment by zocoloco** [comment]
I just purchased a Gold license and there is not an option "new password'
Also, when I add 'reset password' to any form, the fields disappear.

**Comment by dbjpanda** [comment]
This doc is obsolete now. You don't need to create two forms now. Create one form having two form fields "Email" and "Password" and map those in Reset password Action. Password field will be hidden and only be visible when someone clicks on reset password link sent to your Email.

**Comment by zocoloco** [comment]
Still waiting for the refund

**Comment by dbjpanda** [comment]
Refer our new docs [How to create a reset Password form using Elementor?](https://actions-pack.com/docs/create-elementor-reset-password-form)
