### ISSUE TITLE
use google sheet with registration gdpr comaptible - save date and time

### ISSUE THREAD

**Issue by mathevka** [dbjpanda/actions-pack-issue-tracker#27]
Dear DB Panda!

I would like to ask, if there is a possibility to save the date and time of a new registered user to the google sheet, where the data is stored.

It would be absolute helpful for the European GDPR-law.

Thanks a lot!

**Comment by dbjpanda** [comment]
It can be achieved by creating a hidden form field with setting its default value as current date and time. 
<img width="301" alt="Screenshot 2020-07-28 at 5 46 27 AM" src="https://user-images.githubusercontent.com/17483092/88604826-e3df7b00-d095-11ea-8c19-eae38f0c724c.png">
<img width="298" alt="Screenshot 2020-07-28 at 5 46 35 AM" src="https://user-images.githubusercontent.com/17483092/88604830-e641d500-d095-11ea-8795-a89b8b9354ee.png">

**Comment by dbjpanda** [comment]
A Meta Data Option is also added in version 2.0.7
