### ISSUE TITLE
BUG - Ajax - Problems field URL 

### ISSUE THREAD

**Issue by cedche99** [dbjpanda/actions-pack-issue-tracker#29]
Hi,

For my website, i use [bedrock](https://roots.io/bedrock/), so my admin url is : 

> '/wp/wp-admin/'

But in your file /assets/js/google-sheets.js, you make an ajax call with the hard url : 

```php
$.ajax({
            url: '/wp-admin/admin-ajax.php',
            type: 'post',
            dataType: 'json',
            data: {
``` 

So in my configuration the call doesn't work

can you fix this for the next patch

thx

**Comment by dbjpanda** [comment]
Yes. We have already fixed it. And added it to Actions Pack Version 2.0.0 that will be released by next week mostly. Incase you want to fix now. Kindly change the url to `ajaxurl` . If you are not able to do, please send us an email to support@dbjpanda.me. We can do it for you. Thank you

```php
            url: ajaxurl,
            type: 'post',
            dataType: 'json',
            data: {
```

**Comment by cedche99** [comment]
Ok great!
