### ISSUE TITLE
[Translation issue] Elementor Login Widget & Elementor Form Widget

### ISSUE THREAD

**Issue by cornertip** [dbjpanda/actions-pack-issue-tracker#3]
Hi, 

I'm trying to translate these fields to my language (Italian) in the Elementor Login Widget & Elementor Form Widget. 

**LOGIN FORM WIDGET:** 
1. "Remember me" checkmark field is not translatable
2. When I insert wrong or unexisting username, the message: 
"Error: The Username you have entered is incorrect" is not translatable
3. When I don't insert any text in the login fields, the message: 
"Field is required" is not translatable

![login translation](https://user-images.githubusercontent.com/58625922/70373730-27a92880-18eb-11ea-89fa-1430b04aef46.jpg)

**REGISTRATION FORM WIDGET:** 
1. When I insert an existing user or email, the following message "Failed to create new user: xxxxxxxxxxxxx!" is not translatable

![register translation](https://user-images.githubusercontent.com/58625922/70373735-355eae00-18eb-11ea-87e8-325c9625c819.jpg)

-- 

Which path I should search in to find the .pot file or something like that? 
Thanks in advance

**Comment by dbjpanda** [comment]
@cornertip  Can you please specify the choice of language to which you want to translate?

**Comment by cornertip** [comment]
> @cornertip Can you please specify the choice of language to which you want to translate?

Hi dbjpanda, 
I want to translate those strings in Italian Language. 

I put the correct translations below: 

**LOGIN TRANSLATIONS**
ENG - "Error: The Username you have entered is incorrect" 
ITA - "Errore: L'Username inserito non è corretto" 

ENG - "Error: The Password you have entered is incorrect"
ITA - "Errore: La Password inserita non è corretta"

ENG - "This Field is required!" 
ITA - "Questo campo è obbligatorio!"

ENG - "Remember me"
ITA - "Ricordami" 

**FORM TRANSLATIONS**
ENG - "Failed to create new user: Questo nome utente esiste già"
ITA - "Impossibile creare un nuovo utente: questo nome utente esiste già"

ENG - "Failed to create new user: Questo indirizzo email è già utilizzato!"
ITA - "Impossibile creare un nuovo utente: questo indirizzo email è già utilizzato"

--

If you need help for other italian translations, ask me here.

**Comment by dbjpanda** [comment]
Done with translation to your language. Please update Actions Pack plugin version to 1.2.8. 

**Note**: Translation has been done automatically. In case you didn't like the translation, you can do it using a plugin called Loco. We have added the feature to easily translate to your language. Watch the video here https://www.youtube.com/watch?v=6qLkdl97PU0 

Feel free to reopen the issue in case you are facing any issue after the translation.
