### ISSUE TITLE
remember me ( user ) checkbox on login-forms?

### ISSUE THREAD

**Issue by mathevka** [dbjpanda/actions-pack-issue-tracker#7]
Hello, 
I want to know, if it is possible to have a remember-user(name+password) checkbox-field in 
login-forms?

Thank you :-)

**Comment by dbjpanda** [comment]
Implemented in version 1.2.8. Now you can set a Remember me box on Elementor Form Login Action. Thanks for your patience. 

![Screenshot 2019-12-17 at 5 26 08 PM](https://user-images.githubusercontent.com/17483092/70993701-8bed9880-20f2-11ea-9056-82bd89285c1c.png)
![Screenshot 2019-12-17 at 5 26 20 PM](https://user-images.githubusercontent.com/17483092/70993702-8bed9880-20f2-11ea-9710-ad8ea936f3cb.png)
![Screenshot 2019-12-17 at 5 26 36 PM](https://user-images.githubusercontent.com/17483092/70993703-8c862f00-20f2-11ea-9166-32e51820e3f4.png)

![Screenshot 2019-12-17 at 5 28 14 PM](https://user-images.githubusercontent.com/17483092/70993759-aa539400-20f2-11ea-88a2-55e058440e86.png)
