### ISSUE TITLE
Lost Password - Send Email again, when not recieved

### ISSUE THREAD

**Issue by mathevka** [dbjpanda/actions-pack-issue-tracker#8]
Hello,
me again... ,)

is there a way to have a checkbox field in the Lost-Password Form ( need a new one)
when the sent email ( with the pw-reset-link) did not arrive , to tell the form to send a new email with a reset-link again?

Thank you, Eva

**Comment by dbjpanda** [comment]
@mathevka Doesn't it work with the same reset password form by filling your username or email again?

**Comment by dbjpanda** [comment]
@mathevka Reset Password Link has been added now in Version 1.2.9
