### ISSUE TITLE
Login without verification is possible

### ISSUE THREAD

**Issue by olpo24** [dbjpanda/actions-pack-issue-tracker#9]
Hi,

i use the email verification in register process.
I think it should not be possible for a user to log in before verifying his email address.
Now the user get the email to verifying but can also login without verifying.

Best regards,
Ole

**Comment by dbjpanda** [comment]
@olpo24 Thanks for purchasing the plugin.

> I think it should not be possible for a user to log in before verifying his email address.
No, currently it is not possible to login without verifying the email. It is the standard procedure of any user registration form and secure way to onboard your users. 

> Now the user get the email to verifying but can also login without verifying.
It is not supported currently, but I am marking it as a feature request. If you really need this feature we may add it soon. But I would suggest following a standard procedure for better security and user experience.

Let me know, your feedbacks further.

**Comment by olpo24** [comment]
@dbjpanda 
>No, currently it is not possible to login without verifying the email. It is the standard procedure of any user registration form and secure way to onboard your users.

Exactly this behavior has occurred with me. A non-verified user was able to log on. Therefore I unfortunately deactivated the plugin again.

**Comment by dbjpanda** [comment]
The user must have already an account before you activate the plugin on your site. Can you please give me an access to investigate your issue. I have sent you an email. Please reply there. I am closing the issue here. Because it is not advisable to discuss any security-related issue in public.
